#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# generate fernet key for ldap if it doesn't exist
if [[ ! -f "/run/.fernetkey" ]]; then
    if [[ -z "${FERNETKEY}" ]]; then
        KEY=$(python3 /app/fernet-key.py)
        echo "generated fernet key"
    elif ! python3 -c "from cryptography.fernet import Fernet; Fernet(b'${FERNETKEY}').encrypt(b'my deep dark secret')" 2>/dev/null; then
        echo "FERNETKEY env var is not set to a base64 encoded 32-byte key"
        KEY=$(python3 /app/fernet-key.py)
        echo "generated fernet key"
    else
        KEY="${FERNETKEY}"
        echo "using FERNETKEY from env variable"
    fi
    echo "${KEY}" > /run/.fernetkey
fi
