#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8888" \
    s6-setuidgid abc python3 /app/nginx-ldap-auth-daemon.py \
    --host 0.0.0.0 --port 8888
