#!/usr/bin/with-contenv bash
# shellcheck shell=bash

export FERNET_KEY=$(cat /run/.fernetkey)

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8888" \
            s6-setuidgid abc python3 /app/nginx-ldap-auth-daemon.py \
                --host 0.0.0.0 --port 8888
else
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8888" \
            python3 /app/nginx-ldap-auth-daemon.py \
                --host 0.0.0.0 --port 8888
fi
